# main へのpushで本番にデプロイするワークフロー
# - digestでCloud Runに同期デプロイ
# - us-central1 / rag-portfolio-repo に統一
# - 本番も公開（--allow-unauthenticated）
# - 実行SAは prod 用を明示

name: Deploy to Production on Merge

on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'ocr-function/**'
      - '.github/workflows/merge-prod-deploy.yml'

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: serious-timer-467517-e1
  REGION: us-central1
  REPO: rag-portfolio-repo
  RUNTIME_SA_PROD: rag-app-sa-prod@serious-timer-467517-e1.iam.gserviceaccount.com

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - service: ocr-function-prod
            image_name: ocr-function
            context: ./ocr-function
          - service: rag-portfolio-app-prod
            image_name: rag-portfolio-app
            context: ./app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDP }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push (get digest)
        id: build
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          push: true
          tags: |
            ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ matrix.image_name }}:sha-${{ github.sha }}

      - name: Deploy to Cloud Run (by digest)
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ matrix.service }}
          region: ${{ env.REGION }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ matrix.image_name }}@${{ steps.build.outputs.digest }}
          flags: --allow-unauthenticated --service-account=${{ env.RUNTIME_SA_PROD }}

      - name: Show Service URL
        run: echo "Deployed ${{ matrix.service }} -> ${{ steps.deploy.outputs.url }}"
