# PRがCloseされたとき、該当PR用Workspaceをdestroyするワークフロー
# - WIFでGCPに認証
# - pr-<番号> のWorkspaceを選択して破棄
# - 後処理でWorkspaceを削除

name: Destroy Preview Environment on PR Close

on:
  pull_request:
    types: [closed]

permissions:
  id-token: write
  contents: read

env:
  PROJECT_ID: serious-timer-467517-e1
  REGION: us-central1

jobs:
  destroy-preview:
    name: Terraform Destroy (staging)
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.repo.fork == false && github.actor != 'dependabot[bot]' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDP }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform -chdir=terraform init -input=false -reconfigure

      - name: Select Workspace
        run: |
          terraform -chdir=terraform workspace select pr-${{ github.event.pull_request.number }} || exit 0

      - name: Destroy
        run: |
          terraform -chdir=terraform destroy -auto-approve \
            -var="project_id=${{ env.PROJECT_ID }}" \
            -var="region=${{ env.REGION }}" \
            -var-file="staging.tfvars" || true

      - name: Cleanup Workspace
        run: |
          terraform -chdir=terraform workspace select default || true
          terraform -chdir=terraform workspace delete -force pr-${{ github.event.pull_request.number }} || true
