# .github/workflows/pr-app-pipeline.yml

name: Test and Update Application on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'app/**'
      - 'ocr-function/**'
      - 'requirements-dev.txt'
      - '.github/workflows/pr-staging-apptest-deploy.yml'

permissions:
  contents: read
  id-token: write

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -r app/requirements.txt
          pip install -r ocr-function/requirements.txt
      - name: Run unit tests
        run: python3 -m pytest

  update-preview:
    name: Update Application on Staging
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/150327319937/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions-runner@serious-timer-467517-e1.iam.gserviceaccount.com'
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Build and Deploy App to Staging
        run: |
          gcloud builds submit ./app --tag asia-northeast1-docker.pkg.dev/serious-timer-467517-e1/my-app-repo/rag-app:staging-${{ github.sha }}
          gcloud run deploy rag-portfolio-app-staging \
            --image asia-northeast1-docker.pkg.dev/serious-timer-467517-e1/my-app-repo/rag-app:staging-${{ github.sha }} \
            --region asia-northeast1