name: pr-staging-destroy.yml
run-name: "${{ github.workflow }} • ${{ github.ref_name }} • ${{ github.sha }}"

on:
  # 誤実行防止のため、手動実行のみ。実行時に "DESTROY" の入力を必須にする。
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type DESTROY to confirm destroying STAGING infrastructure"
        required: true
        default: ""
        type: string

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: serious-timer-467517-e1
  REGION: us-central1

jobs:
  destroy-staging:
    name: Terraform Destroy (staging) [manual]
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.confirm == 'DESTROY' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDP }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Export Terraform variables (TF_VAR_*)
        shell: bash
        run: |
          echo "TF_VAR_project_id=${PROJECT_ID}"   >> "$GITHUB_ENV"
          echo "TF_VAR_region=${REGION}"           >> "$GITHUB_ENV"
          echo "TF_VAR_environment=staging"        >> "$GITHUB_ENV"
          echo "TF_VAR_source_bucket_name=bkt-${PROJECT_ID}-rag-resource-staging" >> "$GITHUB_ENV"
          echo "TF_VAR_output_bucket_name=bkt-${PROJECT_ID}-rag-output-staging"  >> "$GITHUB_ENV"

      - name: Terraform Init
        run: terraform -chdir=terraform init -input=false -upgrade

      - name: Select Workspace (staging)
        run: terraform -chdir=terraform workspace select staging

      - name: Destroy (staging)
        run: terraform -chdir=terraform destroy -auto-approve -input=false