name: Run Tests on Pull Request

on:
  pull_request:
    branches:
      - main
    paths:
      - 'app/**'
      - 'ocr-function/**'
      - 'requirements-dev.txt'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -r app/requirements.txt
          pip install -r ocr-function/requirements.txt

      - name: Run unit tests
        run: python3 -m pytest